In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
X = df[['Pclass', 'Fare','SibSp']]
y=df['Survived']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train, y_train)

Y_pred = logreg.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score


accuracy_score(y_test, Y_pred)

0.659217877094972

In [ ]:
from sklearn.metrics import confusion_matrix

conf_mtx_nb =confusion_matrix(y_test, Y_pred)

conf_mtx_nb

array([[91, 15],
       [46, 27]])

In [ ]:
from sklearn.model_selection import cross_val_score


np.mean(cross_val_score(LogisticRegression(),X,y,cv=10,scoring="accuracy"))

0.6768789013732833

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, Y_pred)) 

              precision    recall  f1-score   support

           0       0.66      0.86      0.75       106
           1       0.64      0.37      0.47        73

    accuracy                           0.66       179
   macro avg       0.65      0.61      0.61       179
weighted avg       0.66      0.66      0.64       179



In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

Y_pred = knn.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, Y_pred)

0.6368715083798883

In [ ]:
from sklearn.model_selection import cross_val_score

np.mean(cross_val_score(KNeighborsClassifier(),X,y,cv=10,scoring="accuracy"))

0.6600499375780274

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, Y_pred)) 

              precision    recall  f1-score   support

           0       0.70      0.69      0.69       106
           1       0.55      0.56      0.56        73

    accuracy                           0.64       179
   macro avg       0.62      0.63      0.62       179
weighted avg       0.64      0.64      0.64       179



In [ ]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier()

decision_tree.fit(X_train, y_train)

Y_pred = decision_tree.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, Y_pred)

0.6703910614525139

In [ ]:
from sklearn.model_selection import cross_val_score

np.mean(cross_val_score( DecisionTreeClassifier(),X,y,cv=10,scoring="accuracy"))

0.6936329588014981

In [ ]:
from sklearn.ensemble import RandomForestClassifier,VotingClassifier

clf1 = LogisticRegression(multi_class='multinomial', random_state=1)

clf2 = RandomForestClassifier(n_estimators=50, random_state=1)

clf3 =  KNeighborsClassifier(n_neighbors=3)


In [ ]:
eclf1 = VotingClassifier(estimators=[
...         ('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

In [ ]:
eclf1 = eclf1.fit(X_train, y_train)

In [ ]:
Y_pred = eclf1.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, Y_pred)

0.6480446927374302

In [ ]:
from sklearn.metrics import confusion_matrix

conf_mtx_nb = confusion_matrix(y_test, Y_pred)

conf_mtx_nb

array([[87, 19],
       [44, 29]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.66      0.82      0.73       106
           1       0.60      0.40      0.48        73

    accuracy                           0.65       179
   macro avg       0.63      0.61      0.61       179
weighted avg       0.64      0.65      0.63       179



In [ ]:
eclf2 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)],voting='soft')

In [ ]:
eclf2 = eclf2.fit(X_train, y_train)

In [ ]:
Y_pred = eclf2.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, Y_pred)

0.6256983240223464

In [ ]:
from sklearn.metrics import confusion_matrix

conf_mtx_nb = confusion_matrix(y_test, Y_pred)

conf_mtx_nb

array([[81, 25],
       [42, 31]])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.66      0.76      0.71       106
           1       0.55      0.42      0.48        73

    accuracy                           0.63       179
   macro avg       0.61      0.59      0.59       179
weighted avg       0.62      0.63      0.61       179

